name: Laravel Build CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup PHP environment
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'

    - name: Build Environment Check
      run: |
        echo "Iniciando proceso de Build..."
        php -v
        composer --version
        ls -la
        echo "Build completado con Ã©xito."
